source 'https://rubygems.org'

gem "jekyll", "~> 4.3" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem 'liquid', '~> 4.0', '>= 4.0.4' # needed to avoid "Liquid Exception: undefined method `tainted?'"

gem "just-the-docs", "0.4.1" # pinned to the current release
# gem "just-the-docs"        # always download the latest release
